# Generated by Django 3.1.4 on 2021-01-03 16:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('dateofbirth', models.DateField(null=True)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=13, null=True, region=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
